### ISSUE TITLE
tk86 has suffix t and is hard to find by findTCL.cmake

### ISSUE THREAD

**Issue by looooo** [conda-forge/tk-feedstock#12]
we had some hard time finding the right tk because 8.6 has a "t" suffix. If this suffix isn't necessary please compile with:

```
nmake /f makefile.vc SUFX=
```

Also see this post on the FreeCAD forum: 
http://forum.freecadweb.org/viewtopic.php?f=10&t=15197&start=80#p141711

**Comment by jjhelmus** [comment]
There seems to be some discussion of the `tcl86t.dll` vs `tcl86.dll` change in [tcl bug #5082](https://sourceforge.net/p/tcl/bugs/5082/) although from that issue I cannot determine what the recommended name for the DLL should be.  

When building Python on Windows a DLL with the `t` suffix is created for the [tcl](https://hg.python.org/cpython/file/v3.5.2/PCbuild/tcltk.props#l23) and [tk](https://hg.python.org/cpython/file/v3.5.2/PCbuild/tcltk.props#l26) libraries if extenal libraries are built.  If `conda-forge` ever wants to build Python without the these external dependencies, conda-forge/python-feedstock#8, it will need a tk package which provides the `tcl86t.dll` and `tk86t.dll` names. 

Does anyone more familiar with the intricacies of DLL names and TCL/TK have an opinion of what the best naming for these libraries would be or if it is possible (or recommended) to include both options?
