### ISSUE TITLE
matplolib empty figure on OS X when using conda-forge's tk

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/tk-feedstock#36]
From @efiring:

```
So it seems that the problem is not at all dependent on mpl version,
and not really dependent on installation method, either. Instead, it might
depend on the exact tk build:

My original "py37" environment (yielding a plot) had tk 8.6.9-ha92aebf_0
from conda-forge. Now I updated that to match the fresh environment 
("mpl2") version, 8.6.9-h2573ce8_1002, and I get the white screen. 
Switching back to the earlier tk build, I get the plot again.

When I downgrade tk in "mpl2" to 8.5.19, it downgrades a bunch of 
other things including python to 3.6; but the test yields a window, 
and the buttons work!

@ocefpaf it looks like there might be something very fiddly with tk
versions and builds for OSX in conda-forge.
```

Original issue: https://github.com/matplotlib/matplotlib/issues/12074

@efiring I don't have a macOS to test this and I cannot reproduce it on Linux. @conda-forge/tk team: anyone here with a macOS to take a look at this?

**Comment by efiring** [comment]
Possibly related: #30.

**Comment by guyer** [comment]
As far as I can tell, the problem was introduced with build 1001 of 8.6.9:
```
$ conda create -n tk_8.6.9_1000_mpl_2.2.4 --channel conda-forge tk=8.6.9=ha441bb4_1000 matplotlib=2.2.4
$ conda activate tk_8.6.9_1000_mpl_2.2.4
$ MPLBACKEND=TkAgg python -c "from matplotlib import pyplot as plt; plt.plot([1., 2., 3.], [5., 4., 3.]); plt.show()"
```
renders as expected, but
```
$ conda create -n tk_8.6.9_1001_mpl_2.2.4 --channel conda-forge tk=8.6.9=ha441bb4_1001 matplotlib=2.2.4
$ conda activate tk_8.6.9_1001_mpl_2.2.4
$ MPLBACKEND=TkAgg python -c "from matplotlib import pyplot as plt; plt.plot([1., 2., 3.], [5., 4., 3.]); plt.show()"
```
produces a blank window.

Same thing with Matplotlib 3.1.1.

tk 8.6.8 and tk 8.6.9 build 0 and build 1000 are fine. 
tk 8.6.9 build 1001 and build 1002 are not.

macOS 10.14.5 (18F132)

**Comment by efiring** [comment]
Reminder: there are actually two problems related to tk versions. https://github.com/matplotlib/matplotlib/issues/12074#issuecomment-503806135
1) The white window problem, which @guyer narrowed down as starting with 8.6.9 build 1001.
2) Unreliable response to toolbar buttons, which I find in builds 0 and 1000 of 8.6.9, but not in 8.5.19.

**Comment by smithsp** [comment]
I have reports of this on Mac for another tk application.

**Comment by vishalmhjn** [comment]
I am not using conda but pip and virtualenv. I am also facing the same problem as the matplotlib fails to render the plots and python crashes. System details: macOS 10.14.5, Python 3.6, Virtualenv pip

**Comment by Miakatt** [comment]
I don't know if this helps, but I found that running my code with python3 explicitly allows the plotting to work correctly. With python only, the plotting windows are blank. 

```
$ which python
 /Users/me/anaconda3/envs/pmp/bin/python
$ which python3
 /Users/me/anaconda3/envs/pmp/bin/python3

```
Both python and python3:
```
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin

```
Matplotlib version 2.2.3
tk version 8.6.9

**Comment by vishalmhjn** [comment]
@Miakatt  What is your macOS version?

**Comment by Miakatt** [comment]
@vishalmhjn It's Mojave. I'm not at the computer right now to supply the full version number I'm afraid.   I can update on Monday.

**Comment by Miakatt** [comment]
Sorry, I need to make a correction to the above. My plotting works if I use MacOSX backend, but not the default TkAgg backend. 
Using:
`matplotlib.use('MacOSX') `
or setting this in the ~/.matplotlib/matplotlibrc file fixes the plots for me.

**Comment by SandraLum** [comment]
I did an upgrade of python and lib, the following worked for me:

MacOS: mojave 10.14.6
Python: 3.7.4
Virtualenv: 16.7.2
Matplotlib: 3.1.1

```
import matplotlib
matplotlib.use('MacOSX')
from matplotlib import pyplot as plt
```

**Comment by Meteodan** [comment]
I came across this thread searching for why gitk stopped working for me, and I'm convinced now that it is for the same reason as this problem with matplotlib. Specifically, I'm using "gitk" that comes installed with the git mac os x binary (version 2.2.0). When it invokes wish, it uses the version installed with my anaconda3 environment (Tk version 8.6.9) since it is ahead of it in my $PATH, and I get nothing but a blank window. After deactivating my anaconda environment, gitk uses /usr/bin/wish, which is version 8.5, and the window opens correctly.

Before Mojave, this was never an issue, as I recall.

**Comment by mingwandroid** [comment]
Thanks @Meteodan.

While this may be something we should investigate, you should also file a bug with git about gitk if you wouldn't mind?

The bug would be along the lines that software that knows where its other bits live should not use PATH to locate or launch those other bits. It should instead use relative paths from known-to-exist filepaths.

**Comment by Meteodan** [comment]
@mingwandroid 

Yes, of course, I will do so. Thank you for your reply.

**Comment by vishalmhjn** [comment]
> Sorry, I need to make a correction to the above. My plotting works if I use MacOSX backend, but not the default TkAgg backend.
> Using:
> `matplotlib.use('MacOSX') `
> or setting this in the ~/.matplotlib/matplotlibrc file fixes the plots for me.

Thanks for the reply..But this doesn't work on mine. Same problem

**Comment by ocefpaf** [comment]
Looks like this issue is fixed in the latest version. Let's close this and open a new one if we see it again.
